### ISSUE TITLE
How long did it take you to build this?

### ISSUE THREAD

**Issue by despairblue** [x3dom/component-editor#1]
Not really a question but I thought other people might wonder as well, so I rather ask here than via email.

Cheers.

Cool thing btw :+1:

**Comment by mlimper** [comment]
Hm, hard to tell, since we didn't work full time on it... Time was spread over a period around a year or so, with 2-3 people working part-time on it.

Further contributions are welcome, and please feel free to use this editor, or parts of it, for your own apps - and share the result, if you like ;-)
